services:
  postgres:
    image: postgres:17
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "127.0.0.1:5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 10

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped

    ports:
      - "127.0.0.1:6333:6333"

    volumes:
      - qdrant_data:/qdrant/storage

  api:
    build: .
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      QDRANT_URL: http://qdrant:6333

    ports:
      - "127.0.0.1:8000:8000"

    volumes:
      - uploads_data:/app/data/uploads
      - model_cache:/root/.cache/huggingface

    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started

    command:
      - sh
      - -c
      - python -m app.core.init_db && uvicorn app.main:app --host 0.0.0.0 --port 8000


  frontend:
    build: .
    restart: unless-stopped

    environment:
      API_BASE_URL: http://api:8000

    ports:
      - "127.0.0.1:8501:8501"

    depends_on:
      - api

    command:
      - streamlit
      - run
      - frontend/app.py
      - --server.address=0.0.0.0
      - --server.port=8501
      - --server.headless=true



volumes:
  postgres_data:
  qdrant_data:
  uploads_data:
  model_cache:
